app/gardenmatic/seeding/urls.py
"""."""

from django.urls import path

from . import views

urlpatterns = [
    path(r'', views.SeedingListView.as_view(), name='seeding-list'),
    path(
        r'create', views.SeedingCreateView.as_view(),
        name='seeding-create'),
    path(
        r'edit/<int:pk>', views.SeedingUpdateView.as_view(),
        name="seeding-edit"),
    path(
        r'delete/<int:pk>', views.SeedingDeleteView.as_view(),
        name="seeding-delete"),
]

app/gardenmatic/sensor/urls.py
"""."""

from django.urls import path

from . import views

urlpatterns = [
    path(r'', views.SensorListView.as_view(), name='sensor-list'),
    path(
        r'create', views.SensorCreateView.as_view(),
        name='sensor-create'),
    path(
        r'edit/<int:pk>', views.SensorUpdateView.as_view(),
        name="sensor-edit"),
    path(
        r'delete/<int:pk>', views.SensorDeleteView.as_view(),
        name="sensor-delete"),
]

app/gardenmatic/sensor_reading/urls.py
"""."""

from django.urls import path

from . import views

urlpatterns = [
    path(
        r'', views.SensorReadingListView.as_view(),
        name='sensor-reading-list'),
    path(
        r'create', views.SensorReadingCreateView.as_view(),
        name='sensor-reading-create'),
    path(
        r'edit/<int:pk>', views.SensorReadingUpdateView.as_view(),
        name="sensor-reading-edit"),
    path(
        r'delete/<int:pk>', views.SensorReadingDeleteView.as_view(),
        name="sensor-reading-delete"),
]

app/gardenmatic/urls.py
"""."""

from django.urls import path, include

from . import views

app_name = 'gardenmatic'


urlpatterns = [
    path(r'', views.HomeView.as_view(), name='home'),
    path(r'seeding/', include('app.gardenmatic.seeding.urls')),
    path(r'sensor/', include('app.gardenmatic.sensor.urls')),
    path(r'sensor-reading/', include('app.gardenmatic.sensor_reading.urls')),
]

config/urls.py
"""Base URLs."""
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from app.common import errors as middleware
from app.gardenmatic import views

handler500 = middleware.error_500
handler404 = middleware.error_404

router = routers.DefaultRouter()
router.register(
    r'sensores-disponibles', views.SensoresDisponiblesApiViewSet,
    'sensores-disponibles')


urlpatterns = [
    path(r'accounts/', include('allauth.urls')),
    path(r'accounts/', include('app.accounts.urls', namespace='accounts')),
    path(r'api/', include(router.urls)),
    path(r'api/reading-sensor/', views.reading_sensor),
    # path(r'', include('app.site.urls', namespace='site')),
    path(r'', include('app.gardenmatic.urls', namespace='gardenmatic')),
    path(r'api-auth/', include('rest_framework.urls')),
    # path(r'i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    # ...
    # ...
    # If no prefix is given, use the default language
    prefix_default_language=True
)

app/gardenmatic/models.py
# -*- coding: utf-8 -*-

"""Modelos de base de datos de GardenMatic."""

from __future__ import unicode_literals
from datetime import datetime, timedelta, time
from django.db import models
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _
from django.db.models import Min, Max


class Seeding(models.Model):
    """."""

    name = models.CharField(
        max_length=50, null=False, blank=False, verbose_name=_('Name'))
    ambient_humidity_min = models.PositiveIntegerField(
        verbose_name=_('Ambient Humidity Min (%)'))
    ambient_humidity_max = models.PositiveIntegerField(
        verbose_name=_('Ambient Humidity Max (%)'))
    ambient_temperature_min = models.PositiveIntegerField(
        verbose_name=_('Ambient Temperature Min (ºC)'))
    ambient_temperature_max = models.PositiveIntegerField(
        verbose_name=_('Ambient Temperature Max (ºC)'))
    sun_time_min = models.PositiveIntegerField(
        verbose_name=_('Sun Time Min (Hours)'))
    sun_time_max = models.PositiveIntegerField(
        verbose_name=_('Sun Time Max (Hours)'))
    user = models.ForeignKey(
        'accounts.user', null=False, blank=False, on_delete=models.CASCADE)
    size = models.PositiveIntegerField(
        verbose_name=_('Size (Meters)'))
    start_time_reading = models.TimeField(
        null=False, blank=False, verbose_name=_('Start Time Reading'))
    end_time_reading = models.TimeField(
        null=False, blank=False, verbose_name=_('End Time Reading'))
    sensing_time = models.PositiveIntegerField(
        null=False, blank=False, verbose_name=_('Sensing Time (Minutes)'))
    opening_time = models.PositiveIntegerField(
        null=False, blank=False, verbose_name=_('Opening Time (Seconds)'))

    class Meta:
        """."""

        db_table = 'seeding'
        verbose_name = _('Seeding')
        verbose_name_plural = _('Seedings')

    def __str__(self):
        """."""
        return '{}'.format(self.name)

    def get_sensores(self):
        """."""
        return self.sensor_set.all()


class Sensor(models.Model):
    """Modelo del Sensor."""

    SOLENOIDE_VALVE = 'solenoide_valve'
    LIGHT = 'light'
    AMBIENT_HUMIDITY = 'ambient_humidity'
    AMBIENT_TEMPERATURE = 'ambient_temperature'
    GROUND_HUMIDITY = 'ground_humidity'

    TYPE_SENSOR_CHOICE = (
        (SOLENOIDE_VALVE, _('Solenoide Valve')),
        (LIGHT, _('Light Sensor')),
        (AMBIENT_HUMIDITY, _('Ambient Humidity')),
        (AMBIENT_TEMPERATURE, _('Ambient Temperature')),
        (GROUND_HUMIDITY, _('Ground Humidity'))
    )

    GPIO_4_7 = 4
    GPIO_5_29 = 5
    GPIO_6_31 = 6
    GPIO_12_32 = 12
    GPIO_13_33 = 13
    GPIO_16_36 = 16
    GPIO_17_11 = 17
    GPIO_18_12 = 18
    GPIO_19_35 = 19
    GPIO_20_38 = 20
    GPIO_21_40 = 21
    GPIO_22_15 = 22
    GPIO_23_16 = 23
    GPIO_24_18 = 24
    GPIO_25_22 = 25
    GPIO_26_37 = 26
    GPIO_27_13 = 27

    GPIO_PHYSICAL_PINS_CHOICE = (
        (GPIO_4_7, _('GPIO 4 (Physical 7)')),
        (GPIO_5_29, _('GPIO 5 (Physical 29)')),
        (GPIO_6_31, _('GPIO 6 (Physical 31)')),
        (GPIO_12_32, _('GPIO 12 (Physical 32)')),
        (GPIO_13_33, _('GPIO 13 (Physical 33)')),
        (GPIO_16_36, _('GPIO 16 (Physical 36)')),
        (GPIO_17_11, _('GPIO 17 (Physical 11)')),
        (GPIO_18_12, _('GPIO 18 (Physical 12)')),
        (GPIO_19_35, _('GPIO 19 (Physical 35)')),
        (GPIO_20_38, _('GPIO 20 (Physical 38)')),
        (GPIO_21_40, _('GPIO 21 (Physical 40)')),
        (GPIO_22_15, _('GPIO 22 (Physical 15)')),
        (GPIO_23_16, _('GPIO 23 (Physical 16)')),
        (GPIO_24_18, _('GPIO 24 (Physical 18)')),
        (GPIO_25_22, _('GPIO 25 (Physical 22)')),
        (GPIO_26_37, _('GPIO 26 (Physical 37)')),
        (GPIO_27_13, _('GPIO 27 (Physical 13)')),
    )

    seeding = models.ForeignKey(
        Seeding, null=False, blank=False, on_delete=models.CASCADE,
        verbose_name=_('Seeding'))
    name = models.CharField(
        max_length=50, null=False, blank=False, verbose_name=_('Name'))
    pin = models.PositiveIntegerField(
        null=False, blank=False, choices=GPIO_PHYSICAL_PINS_CHOICE,
        verbose_name=_('Pin'))
    status = models.BooleanField(default=False, verbose_name=_('Status'))
    type_sensor = models.CharField(
        max_length=25, null=False, blank=False,
        choices=TYPE_SENSOR_CHOICE, verbose_name=_('Type Sensor'))

    class Meta:
        """."""

        db_table = 'sensor'
        verbose_name = _('Sensor')
        verbose_name_plural = _('Sensors')

    def __str__(self):
        """."""
        return '{}({})'.format(self.name, self.get_type_sensor_display())

    def get_today(self):
        """."""
        today = datetime.now()
        tomorrow = today + timedelta(1)
        today_start = datetime.combine(today, time())
        today_end = datetime.combine(tomorrow, time())
        return today, today_start, today_end

    def get_lecturas(self):
        """."""
        today, today_start, today_end = self.get_today()
        return self.sensorreading_set.filter(
            date_time__lte=today_end, date_time__gte=today_start)

    def get_luminosidad(self):
        """."""
        tiempo_de_sol = 0

        minutos = self.seeding.sensing_time
        luminosidad = self.get_lecturas().filter(
            sensor__type_sensor=self.LIGHT)

        for lum in luminosidad:
            if lum.reading >= 80:
                tiempo_de_sol = tiempo_de_sol + minutos

        return tiempo_de_sol / 60

    def get_luminosidad_text(self):
        """."""
        tiempo_de_sol = self.get_luminosidad()
        horas = int(tiempo_de_sol)
        tiempo_de_sol = int(tiempo_de_sol * 60)
        minutos = tiempo_de_sol % 60
        if minutos == 0:
            return "{} hora(s)".format(horas)
        if horas > 0:
            return format_html(
                "{} hora(s) <br> {} minutos".format(horas, minutos))
        return "{} minutos".format(minutos)

    def get_nublado(self):
        """."""
        tiempo_de_nublado = 0

        minutos = self.seeding.sensing_time
        luminosidad = self.get_lecturas().filter(
            sensor__type_sensor=self.LIGHT)

        for lum in luminosidad:
            if lum.reading < 80:
                tiempo_de_nublado = tiempo_de_nublado + minutos

        return tiempo_de_nublado / 60

    def get_nublado_text(self):
        """."""
        tiempo_nublado = self.get_nublado()
        horas = int(tiempo_nublado)
        tiempo_nublado = int(tiempo_nublado * 60)
        minutos = tiempo_nublado % 60
        if minutos == 0:
            return "{} hora(s)".format(horas)
        if horas > 0:
            return format_html(
                "{} hora(s) <br>{} minutos".format(horas, minutos))
        return "{} minutos".format(minutos)

    def get_temperatura_ambiental_min(self):
        """."""
        temperatura = self.get_lecturas().filter(
            sensor__type_sensor=self.AMBIENT_TEMPERATURE).aggregate(
                Min('reading'))
        return temperatura['reading__min']

    def get_temperatura_ambiental_max(self):
        """."""
        temperatura = self.get_lecturas().filter(
            sensor__type_sensor=self.AMBIENT_TEMPERATURE).aggregate(
                Max('reading'))
        return temperatura['reading__max']

    def get_humedad_ambiental_min(self):
        """."""
        humedad = self.get_lecturas().filter(
            sensor__type_sensor=self.AMBIENT_HUMIDITY).aggregate(
                Min('reading'))
        return humedad['reading__min']

    def get_humedad_ambiental_max(self):
        """."""
        temperatura = self.get_lecturas().filter(
            sensor__type_sensor=self.AMBIENT_HUMIDITY).aggregate(
                Max('reading'))
        return temperatura['reading__max']

    def get_riegos(self):
        """."""
        riegos = self.get_lecturas().filter(
            sensor__type_sensor=self.SOLENOIDE_VALVE, reading=1).count()
        return riegos


class SensorReading(models.Model):
    """."""

    sensor = models.ForeignKey(
        Sensor, null=False, blank=False, on_delete=models.CASCADE,
        verbose_name=_('Sensor'))
    reading = models.FloatField(verbose_name=_('Reading'))
    date_time = models.DateTimeField(auto_now=True)

    class Meta:
        """."""

        db_table = 'sensor_reading'
        verbose_name = _('Sensor Reading')
        verbose_name_plural = _('Sensors Reading')

    def __str__(self):
        """."""
        return '{}'.format(self.sensor.name)

app/gardenmatic/seeding/forms.py
# coding=utf-8
"""Seeding Forms."""
from __future__ import unicode_literals

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div
from app.gardenmatic.models import Seeding


class SeedingForm(forms.ModelForm):
    """."""

    helper = FormHelper()
    helper.method = 'POST'
    helper.form_tag = False
    helper.layout = Layout(
        Div('name', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('size', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('ambient_humidity_min', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('ambient_humidity_max', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div(css_class="row"),
        Div(
            'ambient_temperature_min',
            css_class="col-lg-3 col-md-6 col-sm-12"),
        Div(
            'ambient_temperature_max',
            css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('sun_time_min', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('sun_time_max', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div(css_class="row"),
        Div('start_time_reading', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('end_time_reading', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('sensing_time', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('opening_time', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div(css_class="row"),
    )

    class Meta:
        """Meta class."""

        model = Seeding
        exclude = ['user', ]

    def __init__(self, *args, **kwargs):
        """."""
        super(self.__class__, self).__init__(*args, **kwargs)

app/gardenmatic/sensor_reading/forms.py
# coding=utf-8
"""Sensor Forms."""
from __future__ import unicode_literals

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div
from app.gardenmatic.models import SensorReading, Sensor


class SensorReadingForm(forms.ModelForm):
    """."""

    helper = FormHelper()
    helper.method = 'POST'
    helper.form_tag = False
    helper.html5_required = True
    helper.layout = Layout(
        Div('sensor', css_class="col-md-4"),
        Div('reading', css_class="col-md-4"),
        Div(css_class="row"),
    )

    class Meta:
        """Meta class."""

        model = SensorReading
        exclude = []

    def __init__(self, user, *args, **kwargs):
        """."""
        self.user = user
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields['sensor'].queryset = Sensor.objects.filter(
            seeding__user=self.user)

app/gardenmatic/seeding/views.py
"""Views Seeding."""
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from app.common.mixins import UserPermissionsRequired
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView
)
from django.contrib import messages
from app.gardenmatic.seeding.forms import SeedingForm
from app.gardenmatic import models


class SeedingListView(UserPermissionsRequired, ListView):
    """Listado de Sembradios."""

    model = models.Seeding
    template_name = 'gardenmatic/seeding/list.html'
    paginate_by = 15
    ordering = ['id']

    def get_queryset(self):
        """."""
        queryset = super(SeedingListView, self).get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class SeedingCreateView(UserPermissionsRequired, CreateView):
    """Crear Sembradio."""

    template_name = 'gardenmatic/seeding/create.html'
    model = models.Seeding
    form_class = SeedingForm

    def form_valid(self, form):
        """."""
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super(SeedingCreateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS, _("Successful creation"))
        return reverse('gardenmatic:seeding-list')

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            _("Please correct the error below."))
        return self.render_to_response(self.get_context_data(form=form))


class SeedingUpdateView(UserPermissionsRequired, UpdateView):
    """Actualizar Sembradio."""

    template_name = 'gardenmatic/seeding/edit.html'
    model = models.Seeding
    form_class = SeedingForm
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        """."""
        self.object = form.save(commit=False)
        self.object.save()
        return super(SeedingUpdateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            _("Successful update"))
        if 'save-and-add' in self.request.POST:
            return reverse('gardenmatic:seeding-create')
        else:
            return reverse('gardenmatic:seeding-edit', args=[self.object.id, ])

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            _("Please correct the error below."))
        return self.render_to_response(self.get_context_data(form=form))


class SeedingDeleteView(UserPermissionsRequired, DeleteView):
    """Eliminar Sembradio."""

    template_name = 'gardenmatic/seeding/delete.html'
    model = models.Seeding
    pk_url_kwarg = 'pk'

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            _("Successful delete"))
        return reverse('gardenmatic:seeding-list')

app/gardenmatic/templates/gardenmatic/sensor_reading/create.html
{% extends 'gardenmatic/home.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load static %}
{% get_media_prefix as MEDIA_URL %}
{% get_static_prefix as STATIC_URL %}

{% block title %}
Agregar Sensor Reading
{% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}
<div class="clearfix"><br><br><br></div>
<div class="row">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3>
                Agregar Sensor Reading
            </h3>
        </div>
        <div class="panel-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% crispy form %}
                <div class="col-md-12">
                    <button name="save"  class="btn btn-success text-uppercase" type="submit">
                        <i class="fa fa-save"></i> {% trans 'Save' %}
                    </button>
                    <a class="btn btn-danger text-uppercase" href="{% url 'gardenmatic:sensor-reading-list' %}">
                        <i class="fa fa-close"></i> {% trans 'Cancel' %}
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock scripts %}

app/gardenmatic/templates/gardenmatic/sensor_reading/delete.html
{% extends 'gardenmatic/home.html' %}

{% load i18n %}

{% load static %}

{% get_static_prefix as STATIC_URL %}

{% block style %}
{% endblock %}

{% block title %}
    {% trans 'Delete Sensor Reading' %}
{% endblock %}

{% block content %}
<div class="clearfix"><br><br><br></div>
<div class="row">
	<div class="panel panel-danger">
        <div class="panel-heading">
            <h3>
                {% trans 'Delete Sensor Reading' %}
            </h3>
        </div>
        <div class="panel-body">
        	{% include "common/delete.html" %}
        </div>
    </div>
</div>
{% endblock %}

app/gardenmatic/templates/gardenmatic/sensor_reading/edit.html
{% extends 'gardenmatic/home.html' %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}
{% endblock %}

{% block title %}
{% trans 'Sensor Reading Edit' %}
{% endblock %}

{% block content %}
<div class="clearfix"><br><br><br></div>
<div class="row">
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3>
				{% trans 'Edit Sensor Reading' %}
			</h3>
		</div>
		<div class="panel-body">
			<form action="" method="post" enctype="multipart/form-data">
				{% crispy form %}
				<div class="col-md-12">
					<button name="save"  class="btn btn-success text-uppercase" type="submit">
						<i class="fa fa-save"></i> {% trans 'Update' %}
					</button>
					<a class="btn btn-danger text-uppercase" href="{% url 'gardenmatic:sensor-reading-list' %}">
						<i class="fa fa-close"></i> {% trans 'Cancel' %}
					</a>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

{% block scripts %}
{% endblock %}

app/gardenmatic/templates/gardenmatic/sensor_reading/list.html
{% extends 'gardenmatic/home.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load humanize %}

{% load static %}

{% block title %}
{% trans 'Sensor Reading' %}
{% endblock %}

{% block content %}
<div class="clearfix"><br><br><br></div>
<div class="row">
    <div class="panel-group">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3>
                    {% trans 'Sensor Reading' %}
                    <a href="{% url 'gardenmatic:sensor-reading-create' %}" class="btn btn-success pull-right">
                        <i class="fa fa-plus"></i> {% trans 'Add' %}
                    </a>
                </h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    {% if object_list %}
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>{% trans 'Sensor' %}</th>
                                <th class="text-center">{% trans 'Pin' %}</th>
                                <th class="text-center">{% trans 'Reading' %}</th>
                                <th class="text-center">{% trans 'DateTime' %}</th>
                                <th class="text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for current in object_list %}
                            <tr>
                                <td>
                                    {{ current.sensor.name }} ({{ current.sensor.get_type_sensor_display }})
                                </td>
                                <td class="text-center">
                                    {{ current.sensor.get_pin_display }}
                                </td>
                                <td class="text-center">
                                    {{ current.reading }}
                                </td>
                                <td class="text-center">
                                    {{ current.date_time | date:"d/m/Y H:i a"}}
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'gardenmatic:sensor-reading-edit' current.pk %}" title="{% trans 'Edit' %}" type="button" class="btn btn-sm btn-warning">
                                        <em class="fa fa-pencil"></em> {% trans 'Edit' %}
                                    </a>
                                    <a href="{% url 'gardenmatic:sensor-reading-delete' current.pk %}" title="{% trans 'Delete' %}" type="button" class="btn btn-sm btn-danger">
                                        <em class="fa fa-trash"></em> {% trans 'Delete' %}
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <div class="text-center">
                        <div>
                            <h3>{% trans 'No data to display' %}</h3>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% include 'common/pagination.html' %}
            </div>
        </div>
    </div>
</div>

{% endblock %}