app/gardenmatic/seeding/urls.py
"""."""

from django.urls import path

from . import views

urlpatterns = [
    path(r'', views.SeedingListView.as_view(), name='seeding-list'),
    path(
        r'create', views.SeedingCreateView.as_view(),
        name='seeding-create'),
    path(
        r'edit/<int:pk>', views.SeedingUpdateView.as_view(),
        name="seeding-edit"),
    path(
        r'delete/<int:pk>', views.SeedingDeleteView.as_view(),
        name="seeding-delete"),
]

app/gardenmatic/sensor/urls.py
"""."""

from django.urls import path

from . import views

urlpatterns = [
    path(r'', views.SensorListView.as_view(), name='sensor-list'),
    path(
        r'create', views.SensorCreateView.as_view(),
        name='sensor-create'),
    path(
        r'edit/<int:pk>', views.SensorUpdateView.as_view(),
        name="sensor-edit"),
    path(
        r'delete/<int:pk>', views.SensorDeleteView.as_view(),
        name="sensor-delete"),
]

app/gardenmatic/urls.py
"""."""

from django.urls import path, include

from . import views

app_name = 'gardenmatic'


urlpatterns = [
    path(r'', views.HomeView.as_view(), name='home'),
    path(r'seeding/', include('app.gardenmatic.seeding.urls')),
    path(r'sensor/', include('app.gardenmatic.sensor.urls')),
    path(r'sensor-reading/', include('app.gardenmatic.sensor_reading.urls')),
]

config/urls.py
"""Base URLs."""
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from app.common import errors as middleware
from app.gardenmatic import views

handler500 = middleware.error_500
handler404 = middleware.error_404

router = routers.DefaultRouter()
router.register(
    r'sensores-disponibles', views.SensoresDisponiblesApiViewSet,
    'sensores-disponibles')


urlpatterns = [
    path(r'accounts/', include('allauth.urls')),
    path(r'accounts/', include('app.accounts.urls', namespace='accounts')),
    path(r'api/', include(router.urls)),
    path(r'api/reading-sensor/', views.reading_sensor),
    # path(r'', include('app.site.urls', namespace='site')),
    path(r'', include('app.gardenmatic.urls', namespace='gardenmatic')),
    path(r'api-auth/', include('rest_framework.urls')),
    # path(r'i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    # ...
    # ...
    # If no prefix is given, use the default language
    prefix_default_language=True
)

app/gardenmatic/seeding/forms.py
# coding=utf-8
"""Seeding Forms."""
from __future__ import unicode_literals

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div
from app.gardenmatic.models import Seeding


class SeedingForm(forms.ModelForm):
    """."""

    helper = FormHelper()
    helper.method = 'POST'
    helper.form_tag = False
    helper.layout = Layout(
        Div('name', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('size', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('ambient_humidity_min', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('ambient_humidity_max', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div(css_class="row"),
        Div(
            'ambient_temperature_min',
            css_class="col-lg-3 col-md-6 col-sm-12"),
        Div(
            'ambient_temperature_max',
            css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('sun_time_min', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('sun_time_max', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div(css_class="row"),
        Div('start_time_reading', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('end_time_reading', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('sensing_time', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div('opening_time', css_class="col-lg-3 col-md-6 col-sm-12"),
        Div(css_class="row"),
    )

    class Meta:
        """Meta class."""

        model = Seeding
        exclude = ['user', ]

    def __init__(self, *args, **kwargs):
        """."""
        super(self.__class__, self).__init__(*args, **kwargs)

app/gardenmatic/seeding/views.py
"""Views Seeding."""
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from app.common.mixins import UserPermissionsRequired
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView
)
from django.contrib import messages
from app.gardenmatic.seeding.forms import SeedingForm
from app.gardenmatic import models


class SeedingListView(UserPermissionsRequired, ListView):
    """Listado de Sembradios."""

    model = models.Seeding
    template_name = 'gardenmatic/seeding/list.html'
    paginate_by = 15
    ordering = ['id']

    def get_queryset(self):
        """."""
        queryset = super(SeedingListView, self).get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class SeedingCreateView(UserPermissionsRequired, CreateView):
    """Crear Sembradio."""

    template_name = 'gardenmatic/seeding/create.html'
    model = models.Seeding
    form_class = SeedingForm

    def form_valid(self, form):
        """."""
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super(SeedingCreateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS, _("Successful creation"))
        return reverse('gardenmatic:seeding-list')

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            _("Please correct the error below."))
        return self.render_to_response(self.get_context_data(form=form))


class SeedingUpdateView(UserPermissionsRequired, UpdateView):
    """Actualizar Sembradio."""

    template_name = 'gardenmatic/seeding/edit.html'
    model = models.Seeding
    form_class = SeedingForm
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        """."""
        self.object = form.save(commit=False)
        self.object.save()
        return super(SeedingUpdateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            _("Successful update"))
        if 'save-and-add' in self.request.POST:
            return reverse('gardenmatic:seeding-create')
        else:
            return reverse('gardenmatic:seeding-edit', args=[self.object.id, ])

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            _("Please correct the error below."))
        return self.render_to_response(self.get_context_data(form=form))


class SeedingDeleteView(UserPermissionsRequired, DeleteView):
    """Eliminar Sembradio."""

    template_name = 'gardenmatic/seeding/delete.html'
    model = models.Seeding
    pk_url_kwarg = 'pk'

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            _("Successful delete"))
        return reverse('gardenmatic:seeding-list')

app/gardenmatic/sensor/views.py
"""Views gardenmatic."""
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from app.common.mixins import UserPermissionsRequired
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView
)
from django.contrib import messages
from app.gardenmatic.sensor.forms import SensorForm
from app.gardenmatic import models
from app.gardenmatic.views import BaseFormView


class SensorListView(UserPermissionsRequired, ListView):
    """Listado de Sensores."""

    model = models.Sensor
    template_name = 'gardenmatic/sensor/list.html'
    paginate_by = 15
    ordering = ['id']

    def get_queryset(self):
        """."""
        queryset = super(SensorListView, self).get_queryset()
        queryset = queryset.filter(seeding__user=self.request.user)
        return queryset


class SensorCreateView(UserPermissionsRequired, BaseFormView, CreateView):
    """Crear Sensor."""

    template_name = 'gardenmatic/sensor/create.html'
    model = models.Sensor
    form_class = SensorForm

    def form_valid(self, form):
        """."""
        self.object = form.save(commit=False)
        self.object.save()
        return super(SensorCreateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS, _("Successful creation"))
        return reverse('gardenmatic:sensor-list')

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            _("Please correct the error below."))
        return self.render_to_response(self.get_context_data(form=form))


class SensorUpdateView(UserPermissionsRequired, BaseFormView, UpdateView):
    """Update Sensor."""

    template_name = 'gardenmatic/sensor/edit.html'
    model = models.Sensor
    form_class = SensorForm
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        """."""
        self.object = form.save(commit=False)
        self.object.save()
        return super(SensorUpdateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            _("Successful update"))
        if 'save-and-add' in self.request.POST:
            return reverse('gardenmatic:sensor-create')
        else:
            return reverse('gardenmatic:sensor-edit', args=[self.object.id, ])

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            _("Please correct the error below."))
        return self.render_to_response(self.get_context_data(form=form))


class SensorDeleteView(UserPermissionsRequired, DeleteView):
    """Eliminar sensor."""

    template_name = 'gardenmatic/sensor/delete.html'
    model = models.Sensor
    pk_url_kwarg = 'pk'

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            _("Successful delete"))
        return reverse('gardenmatic:sensor-list')

app/gardenmatic/sensor_reading/views.py
"""Views gardenmatic."""
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from app.common.mixins import AdminPermissionsRequired
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView
)
from django.contrib import messages
from app.gardenmatic.sensor_reading.forms import SensorReadingForm
from app.gardenmatic import models
from app.gardenmatic.views import BaseFormView


class SensorReadingListView(AdminPermissionsRequired, ListView):
    """Listado de Lecturas de sensores."""

    model = models.SensorReading
    template_name = 'gardenmatic/sensor_reading/list.html'
    paginate_by = 15
    ordering = ['id']

    def get_queryset(self):
        """."""
        queryset = super(SensorReadingListView, self).get_queryset()
        return queryset


class SensorReadingCreateView(
        AdminPermissionsRequired, BaseFormView, CreateView):
    """Crear Lectura de sensor."""

    template_name = 'gardenmatic/sensor_reading/create.html'
    model = models.SensorReading
    form_class = SensorReadingForm

    def form_valid(self, form):
        """."""
        self.object = form.save(commit=False)
        self.object.save()
        return super(SensorReadingCreateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS, _("Successful creation"))
        return reverse('gardenmatic:sensor-reading-list')

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            _("Please correct the error below."))
        return self.render_to_response(self.get_context_data(form=form))


class SensorReadingUpdateView(
        AdminPermissionsRequired, BaseFormView, UpdateView):
    """Update Lectura de sensor."""

    template_name = 'gardenmatic/sensor_reading/edit.html'
    model = models.SensorReading
    form_class = SensorReadingForm
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        """."""
        self.object = form.save(commit=False)
        self.object.save()
        return super(SensorReadingUpdateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            _("Successful update"))
        if 'save-and-add' in self.request.POST:
            return reverse('gardenmatic:sensor-reading-create')
        else:
            return reverse(
                'gardenmatic:sensor-reading-edit', args=[self.object.id, ])

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            _("Please correct the error below."))
        return self.render_to_response(self.get_context_data(form=form))


class SensorReadingDeleteView(AdminPermissionsRequired, DeleteView):
    """Eliminar lectura de sensor."""

    template_name = 'gardenmatic/sensor_reading/delete.html'
    model = models.SensorReading
    pk_url_kwarg = 'pk'

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            _("Successful delete"))
        return reverse('gardenmatic:sensor-reading-list')

app/gardenmatic/views.py
"""Views gardenmatic."""
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals
from datetime import datetime
from app.common.mixins import UserPermissionsRequired
from rest_framework.decorators import api_view
from django.utils.translation import ugettext_lazy as _
from rest_framework.exceptions import ValidationError
from django.views.generic.base import TemplateView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import viewsets
from . import models
from . import serializers


class HomeView(UserPermissionsRequired, TemplateView):
    """Home View."""

    template_name = "gardenmatic/dashboard.html"

    def get_context_data(self, **kwargs):
        """Get context data."""
        context = super(HomeView, self).get_context_data(**kwargs)
        today = datetime.now()
        configs = models.Seeding.objects.filter(user=self.request.user)
        context['today'] = today
        context['configs'] = configs

        """
        humedad_ambiente = lecturas_hoy.filter(
            sensor_type=models.Sensor.AMBIENT_HUMIDITY)
        temperatura_ambiente = lecturas_hoy.filter(
            sensor_type=models.Sensor.AMBIENT_TEMPERATURE)
        humedad_tierra = lecturas_hoy.filter(
            sensor_type=models.Sensor.GROUND_HUMIDITY)
        """
        return context


class BaseFormView(object):
    """."""

    def get_form(self, form_class=None):
        """."""
        return self.form_class(
            self.request.user, **self.get_form_kwargs())


@api_view(['POST'])
def reading_sensor(request):
    """Servicio para registrar datos de sensores."""
    pin = request.data.get('pin')
    lectura = request.data.get('lectura')
    tipo_sensor = request.data.get('tipo_sensor')

    if not pin:
        raise ValidationError(_('No se especificó un pin'))
    if not lectura:
        raise ValidationError(_('No hay valor de lectura'))
    if not tipo_sensor:
        raise ValidationError(_('No hay valor de tipo de sensor'))

    try:
        sensor = models.Sensor.objects.filter(
            pin=pin, type_sensor=tipo_sensor)

        reading_sensor = models.SensorReading()
        reading_sensor.sensor = sensor[0]
        reading_sensor.reading = lectura
        reading_sensor.save()

        return Response(
            {'message': _('Lectura guardada con exito')},
            status=status.HTTP_200_OK)

    except models.Sensor.DoesNotExist:
        raise ValidationError(_('El pin del sensor no está registrado'))


class SensoresDisponiblesApiViewSet(viewsets.ModelViewSet):
    """."""

    queryset = models.Sensor.objects.all()
    serializer_class = serializers.SensorSerializer
    allowed_methods = ('GET',)

    def list(self, request, *args, **kwargs):
        """."""
        queryset = self.filter_queryset(self.get_queryset())
        queryset = queryset.filter(status=True)
        page = self.paginate_queryset(queryset)

        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

app/gardenmatic/templates/gardenmatic/seeding/create.html
{% extends 'gardenmatic/home.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %}
Agregar Seeding
{% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}
<div class="clearfix"><br><br><br></div>
<div class="row">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3>
                {% trans 'Agregar Seeding' %}
            </h3>
        </div>
        <div class="panel-body">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.errors}}
                {% crispy form %}
                <br>
                <div class="col-md-12">
                    <button name="save" class="btn btn-success text-uppercase" type="submit">
                        <i class="fa fa-save"></i> {% trans 'Save' %}
                    </button>
                    <a class="btn btn-danger text-uppercase" href="{% url 'gardenmatic:seeding-list' %}">
                        <i class="fa fa-close"></i> {% trans 'Cancel' %}
                    </a>    
                </div>
                
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock scripts %}

app/gardenmatic/templates/gardenmatic/seeding/delete.html
{% extends 'gardenmatic/home.html' %}

{% load i18n %}

{% load static %}

{% get_static_prefix as STATIC_URL %}

{% block style %}
{% endblock %}

{% block title %}
    {% trans 'Delete Seeding' %}
{% endblock %}

{% block content %}
<div class="clearfix"><br><br><br></div>
<div class="row">
	<div class="panel panel-danger">
        <div class="panel-heading">
            <h3>
                {% trans 'Delete Seeding' %}
            </h3>
        </div>
        <div class="panel-body">
        	{% include "common/delete.html" %}
        </div>
    </div>
</div>
{% endblock %}

app/gardenmatic/templates/gardenmatic/seeding/edit.html
{% extends 'gardenmatic/home.html' %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}
{% endblock %}

{% block title %}
{% trans 'Seeding Edit' %}
{% endblock %}

{% block content %}
<div class="clearfix"><br><br><br></div>
<div class="row">
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3>
				{% trans 'Edit Seeding' %}
			</h3>
		</div>
		<div class="panel-body">
			<form action="" method="post" enctype="multipart/form-data">
				{% crispy form %}
				<div class="col-md-12">
					<button name="save"  class="btn btn-success text-uppercase" type="submit">
						<i class="fa fa-save"></i> {% trans 'Update' %}
					</button>
					<a class="btn btn-danger text-uppercase" href="{% url 'gardenmatic:seeding-list' %}">
						<i class="fa fa-close"></i> {% trans 'Cancel' %}
					</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

app/gardenmatic/templates/gardenmatic/seeding/list.html
{% extends 'gardenmatic/home.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load humanize %}

{% load static %}

{% block title %}
SEEDING
{% endblock %}

{% block content %}
<div class="clearfix"><br><br><br></div>
<div class="row">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3>
                {% trans 'List Seeding' %}
                <a href="{% url 'gardenmatic:seeding-create' %}" class="btn btn-success pull-right">
                    <i class="fa fa-plus"></i> {% trans 'Add' %}
                </a>
            </h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
            {% if object_list %}
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Size' %}</th>
                        <th>{% trans 'Sensing Time' %}</th>
                        <th>{% trans 'Opening Time' %}</th>
                        <th class="col-md-2 text-center">{% trans 'Actions' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for current in object_list %}
                    <tr>
                        <td>{{ current.name }}</td>
                        <td>{{ current.size }} Mt(s).</td>
                        <td>{{ current.sensing_time }} Minuto(s)</td>
                        <td>{{ current.opening_time }} Segundo(s)</td>
                        <td class="text-center">
                            <a href="{% url 'gardenmatic:seeding-edit' current.pk %}" title="{% trans 'Edit' %}" type="button" class="btn btn-sm btn-warning">
                                <em class="fa fa-pencil"></em> {% trans 'Edit' %}
                            </a>
                            <a href="{% url 'gardenmatic:seeding-delete' current.pk %}" title="{% trans 'Delete' %}" type="button" class="btn btn-sm btn-danger">
                                <em class="fa fa-trash"></em> {% trans 'Delete' %}
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <div class="text-center">
                <div>
                    <h3>{% trans 'No data to display' %}</h3>
                </div>
            </div>
            {% endif %}
        </div>
        {% include 'common/pagination.html' %}
        </div>
    </div>
</div>
{% endblock %}